#!/bin/bash
# kubctl-0x02
# Deploy blue and green versions and verify logs

#Applying blue and green deployments
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml
kubectl apply -f kubeservice.yaml

echo "Checking running pods"
kubectl get pods -l app=django

echo "Checking logs for green deployment"
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath='{.items[0].metadata.name}')
kubectl logs $GREEN_POD

echo "Blue-Green deployment applied successfully!"
