# render.yaml

services:
  - type: web
    name: messaging-app-web
    env: python
    branch: main
    plan: free
    buildCommand: cd messaging_app && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd messaging_app && gunicorn messaging_app.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: messaging_app.settings
      - key: SECRET_KEY
        value: "<your-django-secret-key>"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "<your-database-url>"
      - key: CELERY_BROKER_URL
        value: redis://:@messaging-app-redis:6379/0

  - type: worker
    name: messaging-app-celery
    env: python
    branch: main
    plan:
